enum AppRoute {
  onboarding('/onboarding'),
  home('/'),
  diet('/diet'),
  dietIntro('/diet/intro'),
  copyMeals('/diet/copy-meals'),
  mealScan('/diet/meal-scan'),
  dietHistory('/diet/history'),
  dietDay('/diet/history/day'),
  recipes('/diet/recipes'),
  recipeForm('/diet/recipes/new'),
  addFood('/diet/add-food'),
  customFood('/diet/food-search/custom-food'),
  water('/water'),
  waterHistory('/water/history'),
  bodyWeight('/body-weight'),
  bodyWeightHistory('/body-weight/history'),
  progressPhotos('/progress-photos'),
  progressPhotoCompare('/progress-photos/compare'),
  sleep('/sleep'),
  sleepHistory('/sleep/history'),
  reminders('/reminders'),
  reminderHistory('/reminders/history'),
  workout('/workout'),
  workoutIntro('/workout/intro'),
  workoutHistory('/workout/history'),
  workoutSummary('/workout/summary'),
  routines('/workout/routines'),
  routineForm('/workout/routines/new'),
  exerciseSearch('/workout/exercise-search'),
  exerciseWorkout('/workout/exercise'),
  exerciseDetail('/workout/exercise-search/detail'),
  exerciseProgressionList('/workout/progression'),
  exerciseProgression('/workout/exercise-progression'),
  profile('/profile'),
  editProfile('/profile/edit'),
  macroGoals('/profile/macro-goals'),
  objective('/profile/objective'),
  paywall('/paywall'),
  settings('/settings'),
  signIn('/auth/sign-in'),
  signUp('/auth/sign-up');

  const AppRoute(this.path);

  final String path;
}
