import 'dart:io';

// Vendors the body-map artwork from react-native-body-highlighter (MIT, see
// THIRD_PARTY_NOTICES.md) into a generated Dart data file. The path data is
// copied verbatim so it can be diffed against upstream; only the slug->part
// grouping is ours. Re-run with:
//
//   git clone --depth 1 https://github.com/HichamELBSI/react-native-body-highlighter
//   BODY_MAP_SOURCE=react-native-body-highlighter dart run tool/import_body_map_paths.dart
const _outputPath = 'lib/app/design_system/components/general/vt_body_map_paths.dart';

// Their slugs are finer than ours in two places and we fold them: the obliques
// are part of what the app calls the abdominals, and the tibialis is the front
// of what it calls the calves. Everything not named here is silhouette detail
// (head, hair, hands, feet, ankles, knees) that the outline already draws.
const _partBySlug = {
  'neck': 'neck',
  'trapezius': 'trapezius',
  'deltoids': 'deltoids',
  'chest': 'chest',
  'abs': 'abs',
  'obliques': 'abs',
  'biceps': 'biceps',
  'triceps': 'triceps',
  'forearm': 'forearm',
  'upper-back': 'upperBack',
  'lower-back': 'lowerBack',
  'gluteal': 'gluteal',
  'adductors': 'adductors',
  'quadriceps': 'quadriceps',
  'hamstring': 'hamstring',
  'calves': 'calves',
  'tibialis': 'calves',
};

const _sources = {
  ('male', 'front'): 'assets/bodyFront.ts',
  ('male', 'back'): 'assets/bodyBack.ts',
  ('female', 'front'): 'assets/bodyFemaleFront.ts',
  ('female', 'back'): 'assets/bodyFemaleBack.ts',
};

const _wrappers = {'male': 'components/SvgMaleWrapper.tsx', 'female': 'components/SvgFemaleWrapper.tsx'};

void main() {
  final source = Platform.environment['BODY_MAP_SOURCE'];
  if (source == null) {
    stderr.writeln('Set BODY_MAP_SOURCE to a checkout of react-native-body-highlighter.');
    exitCode = 1;
    return;
  }

  final outlines = <String, Map<String, String>>{};
  for (final MapEntry(key: figure, value: path) in _wrappers.entries) {
    final wrapper = File('$source/$path').readAsStringSync();
    final paths = RegExp('d="([^"]+)"').allMatches(wrapper).map((match) => match.group(1)!).toList();
    if (paths.length < 2) {
      throw StateError('Expected a front and a back outline in $path, found ${paths.length}.');
    }
    outlines[figure] = {'front': paths[0], 'back': paths[1]};
  }

  final parts = <(String, String), Map<String, List<String>>>{};
  for (final MapEntry(key: (figure, view), value: path) in _sources.entries) {
    parts[(figure, view)] = _partsOf(File('$source/$path').readAsStringSync());
  }

  File(_outputPath).writeAsStringSync(_render(outlines, parts));
  stdout.writeln('Wrote $_outputPath');
}

Map<String, List<String>> _partsOf(String contents) {
  final slugs = RegExp(r'slug:\s*"([a-z-]+)"').allMatches(contents).toList();
  final pathsByPart = <String, List<String>>{};
  for (final (index, slug) in slugs.indexed) {
    final part = _partBySlug[slug.group(1)!];
    if (part == null) {
      continue;
    }
    final block = contents.substring(slug.end, index + 1 < slugs.length ? slugs[index + 1].start : contents.length);
    final paths = RegExp('"([MmZz][^"]*)"').allMatches(block).map((match) => match.group(1)!);
    pathsByPart.putIfAbsent(part, () => []).addAll(paths);
  }
  return pathsByPart;
}

String _render(Map<String, Map<String, String>> outlines, Map<(String, String), Map<String, List<String>>> parts) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/import_body_map_paths.dart. Do not edit by hand.')
    ..writeln('// Artwork from react-native-body-highlighter (MIT) - see THIRD_PARTY_NOTICES.md.')
    ..writeln()
    ..writeln("import 'package:flutter/material.dart';")
    ..writeln("import 'package:vitta/app/design_system/components/general/vt_body_figure.dart';")
    ..writeln("import 'package:vitta/app/design_system/components/general/vt_body_map_view.dart';")
    ..writeln("import 'package:vitta/app/design_system/components/general/vt_body_part.dart';")
    ..writeln()
    ..writeln('abstract class VTBodyMapPaths {')
    ..writeln('  static const Size designSize = Size(724, 1448);')
    ..writeln()
    ..writeln('  static const Map<VTBodyMapView, double> viewOriginX = {VTBodyMapView.front: 0, VTBodyMapView.back: 724};')
    ..writeln()
    ..writeln('  static const Map<VTBodyFigure, Map<VTBodyMapView, String>> outline = {');
  for (final MapEntry(key: figure, value: byView) in outlines.entries) {
    buffer.writeln('    VTBodyFigure.$figure: {');
    for (final MapEntry(key: view, value: path) in byView.entries) {
      buffer.writeln("      VTBodyMapView.$view: '${_escape(path)}',");
    }
    buffer.writeln('    },');
  }
  buffer
    ..writeln('  };')
    ..writeln()
    ..writeln('  static const Map<VTBodyFigure, Map<VTBodyMapView, Map<VTBodyPart, List<String>>>> parts = {');
  for (final figure in ['male', 'female']) {
    buffer.writeln('    VTBodyFigure.$figure: {');
    for (final view in ['front', 'back']) {
      buffer.writeln('      VTBodyMapView.$view: {');
      final byPart = parts[(figure, view)]!;
      for (final part in _paintOrder) {
        final paths = byPart[part];
        if (paths == null) {
          continue;
        }
        buffer.writeln('        VTBodyPart.$part: [');
        for (final path in paths) {
          buffer.writeln("          '${_escape(path)}',");
        }
        buffer.writeln('        ],');
      }
      buffer.writeln('      },');
    }
    buffer.writeln('    },');
  }
  buffer
    ..writeln('  };')
    ..writeln('}');
  return buffer.toString();
}

const _paintOrder = [
  'lowerBack',
  'upperBack',
  'trapezius',
  'neck',
  'deltoids',
  'chest',
  'abs',
  'biceps',
  'triceps',
  'forearm',
  'gluteal',
  'adductors',
  'quadriceps',
  'hamstring',
  'calves',
];

String _escape(String path) => path.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(RegExp(r'\s+'), ' ').trim();
